const appname = "E Mart ";
const appversion = "Version 1.0.0";
const credits = "@Mohsin Naseer";
const email = "Email";
const emailhint = "abc@example.com";
const password = "Password";
const passwordhint = "********";
const login = "Log in";
const signup = "Sign up";
const createNewAccount = "Create a new Account";
const loginWith = "Log in with";
const forgetPass = "Forget Password";
const retypePassword = "Retype Password";
const name = "Name";
const nameHint = "Your Name";
const privacyPolicy = "Privacy Policy";
const termAndCond = "Terms & Conditions";
const haveAccount = "Already have an Account? ";
const home = "Home",
    categories = "Category",
    cart = "Cart",
    account = "Account";
